#!/usr/bin/env bash
# Creates a redirection
sudo apt-get install -y nginx
new="server_name _;;\n\trewrite \/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4;"
sudo sed -i "s/localhost;/$new/" /etc/nginx/sites-available/default
sudo service nginx restart
