#!/usr/bin/env bash
# Creates a redirection
sudo apt-get install -y nginx
new="54.236.25.188;\n\tlocation \/redirect_me{\n\t\treturn 301 http:\/\/www.google.com;}"
sed -i "s/localhost;/$new/" /etc/nginx/sites-available/default
sudo service nginx restart
