#!/usr/bin/env bash
# Displays 'Best School'. Displays Hi on the 9th iteration

s="Best School"
count=0

while [ $count -lt 10 ];
do
	if [[ $count -eq 9 ]];
	then
		echo "Hi"
	fi
	echo "$s"
	((count++))
done
