#!/usr/bin/env bash

s="Best School"
count=0

while [ $count -lt 10 ];
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"
		
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "$s"
	fi
	((count++))
done
